version: '3.8'
services:
  app:
    image: photoblog-prod
    build: 
      context: .
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production

