version: '3.8'
services:
  app:
    image: photoblog-dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/dock/app
      - ./public:/dock/public
      - ./lib:/dock/lib
    command: sh -c "npm run dev"
    environment:
      NODE_ENV: development
