version: '3.8'
services:
  app:
    image: photoblog-tests
    build: 
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 3000:3000
    volumes:
      - ./app:/dock/app
      - ./public:/dock/public
      - ./lib:/dock/lib

    command: sh -c "npm run test" # && npm run test
    environment:
      NODE_ENV: tests

