version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: photoblogPostgres
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: development
  app:
    image: photoblog-dev
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/dock/app
      - ./public:/dock/public
      - ./lib:/dock/lib
    command: sh -c "npm run dev"
    environment:
      NODE_ENV: development
